---
- name: export asm config
  hosts: f5
  connection: local
  gather_facts: false
  vars:
    provider:
      server: "{{private_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: 443
      validate_certs: false

  tasks:
    - name: Verify the system was installed
      bigip_asm_policy_fetch:
        name: asm_name
        file: asm_name
        dest: /root/download
        provider: "{{ provider }}"
