---
- name: import asm config
  hosts: lb
  connection: local
  vars:
    provider:
      server: "{{private_ip}}"
      user: "{{ansible_user}}"
      password: "{{ansible_ssh_pass}}"
      server_port: 443
      validate_certs: false

  tasks:
    - name: import asm policy
      bigip_asm_policy:
        name: demo
        file: /Volumes/GoogleDrive/My Drive/Projects/f5/f5-asm-ansible-export-import/demo.xml
        active: yes
        state: present
        provider: "{{ provider }}"

